### ISSUE TITLE
Enhancement - Employee

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#150]
### Todo's

- [x] #180
- [x] #179
- [x] #181
- [ ] Write Baseline Profile
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
