### ISSUE TITLE
Enhancement - Product

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#153]
### Todo's

- [x] #191
- [x] #192
- [x] #193
- [x] #194
- [x] #195
- [x] #197
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
