### ISSUE TITLE
Enhancement - Category

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#154]
### Todo's

- [x] #199
- [x] #200
- [x] #201
- [ ] Add New Category Details Feature
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
