### ISSUE TITLE
Enhancement - Orders

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#155]
### Todo's

- [ ] Fix Order Screen UI/UX
- [ ] Fix Add Edit Order Screen UI/UX
- [ ] Remove Unnecessary functions
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
