### ISSUE TITLE
Enhancement - Cart

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#156]
### Todo's

- [ ] Fix Cart Screen UI/UX
- [x] #203
- [ ] Improve Performance
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
