### ISSUE TITLE
Enhancement - Reports

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#158]
### Todo's

- [ ] Fix Reports Screen UI/UX
- [ ] Remove Unnecessary functions
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
