### ISSUE TITLE
Enhancement - Profile

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#159]
### Todo's

- [x] #210
- [x] #211
- [ ] Remove Unnecessary functions
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
