### ISSUE TITLE
Enhancement - Settings

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#160]
### Todo's

- [ ] Fix Settings Screen UI/UX
- [ ] Remove Unnecessary functions
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
