### ISSUE TITLE
Enhancement - Reminder

### ISSUE THREAD

**Issue by niyajali** [skniyajali/POS-Application#161]
### Todo's

- [ ] Fix Reminder Screen UI/UX
- [ ] Fix Absent Reminder Screen UI/UX
- [ ] Fix Salary Reminder Screen UI/UX
- [ ] Remove Unnecessary functions
- [ ] Write Baseline Profile for this feature
- [ ] Write Instrument Test Cases
- [ ] Write Unit Test Cases
